### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by g1bber1sh** [xynium/webfeed#2]
hi
i cant get this working with any of my feeds
such as https://forum.endeavouros.com/latest.rss and https://archlinux.org/feeds/news/
can this be fixed?
or is there something i misunderstood?

**Comment by xynium** [comment]
![Capture d’écran du 2022-11-15 17-33-11](https://user-images.githubusercontent.com/19983942/201974655-830b6f86-3baf-4549-91a1-6ac964e2b441.png)
Hi,
For your first link All doing OK
JP

**Comment by g1bber1sh** [comment]
its simply not working here, and after a while it disappears from the panel. the extensions app says 'Soup.SessionAsync is not a constructor' with a red "!"
am i missing a needed package?

**Comment by xynium** [comment]
Hi,
What is your gnome version  and linux distro. I run ubuntu 20 with gnome 42.4.
JP

**Comment by g1bber1sh** [comment]
endeavouros (arch) rolling, gnome 43, linux 6.0.8

**Comment by xynium** [comment]
see
https://www.reddit.com/r/gnome/comments/xt0jwz/gnome_43_soup_30_gnome_extensions_stockextension/
It was said that Soup (that deal with the connection) should work on gnome 43. But...
I will make the correction but not before 1 or 2 week.

**Comment by g1bber1sh** [comment]
thank you ! i hope you can fix it :)

**Comment by g1bber1sh** [comment]
hi
that seems to work now but i cant expand the feed menus
see https://i.imgur.com/7M1ONSU.png

**Comment by xynium** [comment]
Hi,
It mean that the time (emission of the RSS info) is later than the delay from the preference box.
And some time the feed is updated with old information.
I have for those case to suppress the ">" because info are too old (according of user choose)
JP

De : "g1bber1sh"
A : "xynium/webfeed" ,"Jean Pierre Lathuile" ,"Comment"
Envoyé: dimanche 18 Décembre 2022 09:43
Objet : Re: [xynium/webfeed] not working (Issue #2)
 

 

hi
that seems to work now but i cant expand the feed menus
see https://i.imgur.com/7M1ONSU.png

**Comment by g1bber1sh** [comment]
ah i understand, yes its working now
but maybe this extension should have a button for marking feeds read/old?

**Comment by xynium** [comment]
Hi,
Extension should stay simple and "intuitive" to use.
The "timeout" way of filtering is (on my pts of view) simple to code and efficient
